export const FIELDS = [
  "Artificial Intelligence",
  "Back End",
  "Blockchain",
  "Cloud Computing",
  "Computer Architecture",
  "Cybersecurity",
  "Data Science",
  "Databases",
  "DevOps",
  "Front End",
  "Game Development",
  "IoT",
  "Machine Learning",
  "Mobile Development",
  "Networking",
  "Operating Systems",
  "Programming Language",
  "Robotics",
  "VR/AR",
  "Web Development",
  "Other",
];
