export const TOPICS = [
  "React",
  "Angular",
  "Vue.js",
  "Node.js",
  "Django",
  "Ruby on Rails",
  "ASP.NET",
  "Spring",
  "Flask",
  "Express.js",
  "Laravel",
  "Symfony",
  "Hibernate",
  "Flutter",
  "ASP.NET Core",
  "Play",
  "Ember.js",
  "CakePHP",
  "CodeIgniter",
  "Zend Framework",
  "RubyMotion",
  "Meteor",
  "Gatsby",
  "Next.js",
  "NestJS",
  "Quarkus",
  "Struts",
  "Grails",
  "Redux",
  "React Router",
  "Axios",
  "Formik",
  "Yup",
  "Styled Components",
  "Material-UI",
  "Chakra UI",
  "Ant Design",
  "React Query",
  "React Hook Form",
  "React Helmet",
  "React Icons",
  "React Testing Library",
  "Jest",
  "Enzyme",
  "Storybook",
  "Create React App",
  "Parcel",
  "Babel",
  "ESLint",
  "Prettier",
  "Husky",
  "Lint-Staged",
  "React Native",
  "Expo",
  "React Navigation",
  "React Native Elements",
  "React Native Paper",
  "React Native Maps",
  "React Native Gesture Handler",
  "jQuery",
  "TensorFlow",
  "NumPy",
  "Pandas",
  "SciPy",
  "Keras",
  "OpenCV",
  "Matplotlib",
  "PyTorch",
  "Lodash",
  "Bootstrap",
  "D3.js",
  "Gulp",
  "Webpack",
  "Vite",
  "RxJS",
  "Mocha",
  "JUnit",
  "Mockito",
  "Selenium",
  "Log4j",
  "SLF4J",
  "Gson",
  "Jackson",
  "Glide",
  "Picasso",
  "Python",
  "JavaScript",
  "Java",
  "C",
  "C++",
  "C#",
  "Ruby",
  "Go",
  "Swift",
  "Kotlin",
  "Rust",
  "PHP",
  "TypeScript",
  "Perl",
  "Objective-C",
  "Scala",
  "Haskell",
  "Lua",
  "Shell",
  "R",
  "MATLAB",
  "Groovy",
  "VB.NET",
  "Dart",
  "Julia",
  "PowerShell",
  "Elixir",
  "Clojure",
  "F#",
  "Scheme",
  "Object-Oriented Programming",
  "Data Structures",
  "Algorithms",
  "Database Management",
  "Web Development",
  "Mobile App Development",
  "Network Programming",
  "Operating Systems",
  "Software Testing",
  "Version Control Systems",
  "Cybersecurity",
  "Artificial Intelligence",
  "Machine Learning",
  "Data Science",
  "Cloud Computing",
  "IoT",
  "Internet of Things",
  "Blockchain",
  "Game Development",
  "Natural Language Processing",
  "Parallel Programming",
  "Computer Graphics",
  "Functional Programming",
  "Software Development Life Cycle",
  "Agile Methodologies",
  "User Interface Design",
  "Responsive Web Design",
  "Performance Optimization",
  "Debugging",
  "Troubleshooting",
  "AI",
  "ML",
  "Web Dev",
  "MongoDB",
  "MySQL",
  "PostgreSQL",
  "SQLite",
  "Firebase",
  "DynamoDB",
  "Cassandra",
  "Redis",
  "Elasticsearch",
  "Neo4j",
  "CouchDB",
  "RethinkDB",
  "MariaDB",
  "Microsoft SQL Server",
  "Oracle Database",
  "IBM DB2",
  "SAP HANA",
  "Teradata",
  "MongoDB Atlas",
  "Amazon Aurora",
  "Amazon Redshift",
  "Azure SQL Database",
  "Google Cloud SQL",
  "Databricks",
  "Snowflake",
  "Apache HBase",
  "Apache Hive",
  "PrestoDB",
  "Apache Ignite",
  "AWS Lambda",
  "Amazon S3",
  "Amazon EC2",
  "Amazon DynamoDB",
  "AWS Amplify",
  "Amazon API Gateway",
  "AWS CloudFormation",
  "Amazon SNS",
  "Amazon SQS",
  "AWS Elastic Beanstalk",
  "Amazon Kinesis",
  "AWS Fargate",
  "Amazon SageMaker",
  "AWS CloudWatch",
  "Amazon Cognito",
  "Unity",
  "Unreal Engine",
  "Cocos2D",
  "Construct",
  "GameMaker Studio",
  "Godot",
  "Lumberyard",
  "CryEngine",
  "Blender",
  "Maya",
  "3ds Max",
  "ZBrush",
  "Substance Painter",
  "Photoshop",
  "Spine",
  "PixiJS",
  "Phaser",
  "Mongoose",
  "Other",
];
