export const TOPICS = [
  "3ds Max",
  "Algorithms",
  "Amazon Aurora",
  "Amazon Redshift",
  "Angular",
  "Ant Design",
  "Apache HBase",
  "Apache Hive",
  "Apache Ignite",
  "Artificial Intelligence",
  "ASP.NET",
  "ASP.NET Core",
  "AstroJS",
  "AWS",
  "AWS Lambda",
  "Axios",
  "Azure SQL Database",
  "Babel",
  "Blender",
  "Blockchain",
  "Bootstrap",
  "C",
  "C#",
  "C++",
  "CakePHP",
  "Cassandra",
  "Chakra UI",
  "Clojure",
  "Cloud Computing",
  "Cocos2D",
  "CodeIgniter",
  "Computer Graphics",
  "Construct",
  "CouchDB",
  "Create React App",
  "CryEngine",
  "CSS",
  "Cybersecurity",
  "D3.js",
  "Dart",
  "Data Science",
  "Data Structures",
  "Database",
  "Databricks",
  "Debugging",
  "Django",
  "Docker",
  "DynamoDB",
  "Elasticsearch",
  "Elixir",
  "Ember.js",
  "Enzyme",
  "ESLint",
  "Expo",
  "Express.js",
  "F#",
  "Firebase",
  "Flask",
  "Flutter",
  "Formik",
  "Functional Programming",
  "Game Development",
  "GameMaker Studio",
  "Gatsby",
  "GIT",
  "Glide",
  "Go",
  "Godot",
  "Google Cloud SQL",
  "Grails",
  "Groovy",
  "Gson",
  "Gulp",
  "Haskell",
  "Hibernate",
  "HTML",
  "Husky",
  "Internet of Things",
  "Jackson",
  "Java",
  "JavaScript",
  "Jest",
  "jQuery",
  "Julia",
  "JUnit",
  "Keras",
  "Kotlin",
  "Laravel",
  "Lint-Staged",
  "Lodash",
  "Log4j",
  "Lua",
  "Lumberyard",
  "Machine Learning",
  "MariaDB",
  "Material-UI",
  "MATLAB",
  "Matplotlib",
  "Maya",
  "Meteor",
  "Microsoft SQL Server",
  "Mobile App Development",
  "Mocha",
  "Mockito",
  "MongoDB",
  "MongoDB Atlas",
  "Mongoose",
  "MySQL",
  "Natural Language Processing",
  "Neo4j",
  "NestJS",
  "Network Programming",
  "Next.js",
  "Node.js",
  "NumPy",
  "Nuxt.js",
  "Object-Oriented Programming",
  "Objective-C",
  "OpenCV",
  "OpenGL",
  "Operating Systems",
  "Oracle Database",
  "Pandas",
  "Parallel Programming",
  "Parcel",
  "Performance Optimization",
  "Perl",
  "Phaser",
  "PHP",
  "Picasso",
  "PixiJS",
  "Play",
  "PostgreSQL",
  "PowerShell",
  "PrestoDB",
  "Prettier",
  "Python",
  "PyTorch",
  "Quarkus",
  "R",
  "React",
  "React Helmet",
  "React Hook Form",
  "React Icons",
  "React Native",
  "React Native",
  "React Query",
  "React Router",
  "React Testing Library",
  "Redis",
  "Redux",
  "Responsive Web Design",
  "RethinkDB",
  "Ruby",
  "Ruby on Rails",
  "RubyMotion",
  "Rust",
  "RxJS",
  "Scala",
  "Scheme",
  "SciPy",
  "Selenium",
  "Shell",
  "SLF4J",
  "Snowflake",
  "Software Development Life Cycle",
  "Software Testing",
  "Spine",
  "Spring",
  "SQLite",
  "Storybook",
  "Struts",
  "Styled Components",
  "Substance Painter",
  "Svelte",
  "Swift",
  "Symfony",
  "TailwindCSS",
  "TensorFlow",
  "Three.js",
  "Troubleshooting",
  "TypeScript",
  "Unity",
  "Unreal Engine",
  "VB.NET",
  "Version Control Systems",
  "Vite",
  "Vue.js",
  "Web Development",
  "Webpack",
  "Yup",
  "ZBrush",
  "Zend Framework",
  "Other",
];
